nextflow_binary = "/usr/local/bin/nextflow"
nextflow_config_file="/home/dlejeune/Projects/deepleap/nextflow.config"
nextflow_work_dir="/home/dlejeune/tmp/work"
nextflow_cache_dir="/home/dlejeune/tmp/cache"
nextflow_main_script="/home/dlejeune/Projects/deepleap/main.nf"
nextflow_log_path = "/home/dlejeune/tmp/nextflow.log"
data_dir = "temp/"
max_memory = "16.GB"
max_cpus = "16"
max_time = "24.h"
